// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	entity "github.com/erikrios/reog-apps-apis/entity"
	mock "github.com/stretchr/testify/mock"
)

// VillageRepository is an autogenerated mock type for the VillageRepository type
type VillageRepository struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: id
func (_m *VillageRepository) FindByID(id string) (entity.Village, error) {
	ret := _m.Called(id)

	var r0 entity.Village
	if rf, ok := ret.Get(0).(func(string) entity.Village); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.Village)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
