version: "3.9"
services:
  db:
    image: postgres:alpine
    restart: always
    container_name: reog-apps-db 
    environment:
      POSTGRES_USER: 'erikrios'
      POSTGRES_PASSWORD: 'erikrios'
      POSTGRES_DB: 'reog_apps_db'
    ports: 
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - reog-apps-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  logging:
    image: mongo:5.0.8
    restart: always
    container_name: mongo-logging
    environment:
      MONGO_INITDB_ROOT_USERNAME: erikrios 
      MONGO_INITDB_ROOT_PASSWORD: erikrios
      MONGO_INITDB_DATABASE: logging
    ports: 
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - reog-apps-logging-volume:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  api:
    image: "erikrios/reog-apps-apis:1.0"
    restart: always
    container_name: reog-apps-apis
    environment:
      ENV: 'development'
      PORT: '3000'
      DB_PORT: '5432'
      DB_HOST: 'reog-apps-db'
      DB_USER: 'erikrios'
      DB_PASSWORD: 'erikrios'
      DB_NAME: 'reog_apps_db'
      JWT_SECRET: 'ErikRioSetiawan'
      PONOROGO_ADMINISTRATIVE_AREA_BASE_URL: 'https://ponorogo-api.herokuapp.com/api/v1'
      ADMIN_USERNAME: 'admin'
      ADMIN_NAME: 'administrator'
      ADMIN_PASSWORD: 'erikrios'
      MONGO_USERNAME: 'erikrios'
      MONGO_PASSWORD: 'erikrios'
      MONGO_HOST: 'mongo-logging'
      MONGO_PORT: '27017'
    ports: 
      - '3000:3000'
    expose:
      - '3000'
    depends_on:
      db:
        condition: service_healthy
      logging:
        condition: service_healthy
volumes:
  reog-apps-db-volume:
  reog-apps-logging-volume:
