version: "3.9"
services:
  db:
    image: postgres:alpine
    restart: always
    container_name: reog-apps-db 
    environment:
      POSTGRES_USER: 'erikrios'
      POSTGRES_PASSWORD: 'erikrios'
      POSTGRES_DB: 'reog_apps_db'
    ports: 
      - '5432:5432'
    expose:
      - '5432'
