// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/erikrios/reog-apps-apis/entity"
	mock "github.com/stretchr/testify/mock"
)

// AdminRepository is an autogenerated mock type for the AdminRepository type
type AdminRepository struct {
	mock.Mock
}

// FindByUsername provides a mock function with given fields: ctx, username
func (_m *AdminRepository) FindByUsername(ctx context.Context, username string) (entity.Admin, error) {
	ret := _m.Called(ctx, username)

	var r0 entity.Admin
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.Admin); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(entity.Admin)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
