// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"

	payload "github.com/erikrios/reog-apps-apis/model/payload"
	mock "github.com/stretchr/testify/mock"
)

// AdminService is an autogenerated mock type for the AdminService type
type AdminService struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, credential
func (_m *AdminService) Login(ctx context.Context, credential payload.Credential) (string, error) {
	ret := _m.Called(ctx, credential)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, payload.Credential) string); ok {
		r0 = rf(ctx, credential)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, payload.Credential) error); ok {
		r1 = rf(ctx, credential)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
