// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Logging is an autogenerated mock type for the Logging type
type Logging struct {
	mock.Mock
}

// Error provides a mock function with given fields: message
func (_m *Logging) Error(message string) {
	_m.Called(message)
}
