// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// TokenGenerator is an autogenerated mock type for the TokenGenerator type
type TokenGenerator struct {
	mock.Mock
}

// ExtractToken provides a mock function with given fields: c
func (_m *TokenGenerator) ExtractToken(c echo.Context) (string, string) {
	ret := _m.Called(c)

	var r0 string
	if rf, ok := ret.Get(0).(func(echo.Context) string); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(echo.Context) string); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Get(1).(string)
	}

	return r0, r1
}

// GenerateToken provides a mock function with given fields: id, username
func (_m *TokenGenerator) GenerateToken(id string, username string) (string, error) {
	ret := _m.Called(id, username)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(id, username)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(id, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
