basePath: /api/v1
host: localhost
info:
  contact:
    email: erikriosetiawan15@gmail.com
    name: Erik Rio Setiawan
    url: http://www.swagger.io/support
  description: API for Reog Group in Ponorogo
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Reog Apps API
  version: "1.0"
paths: {}
swagger: "2.0"
