// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"

	payload "github.com/erikrios/reog-apps-apis/model/payload"
	mock "github.com/stretchr/testify/mock"
)

// AddressService is an autogenerated mock type for the AddressService type
type AddressService struct {
	mock.Mock
}

// Update provides a mock function with given fields: ctx, id, p
func (_m *AddressService) Update(ctx context.Context, id string, p payload.UpdateAddress) error {
	ret := _m.Called(ctx, id, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, payload.UpdateAddress) error); ok {
		r0 = rf(ctx, id, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
