name: Continuous Delivery

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ini-jobs-cd:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.DOCKERHUB_USERNAME }}
      - run: echo ${{ secrets.DOCKERHUB_TOKEN }}
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: erikrios/reog-apps-apis:1.0

      - name: SSH to VM instance and redeploy Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker-compose down
            docker image rm erikrios/reog-apps-apis:1.0
            docker-compose up -d
